theme = "rose_pine_moon"

[editor]
line-number = "relative"
mouse = false
color-modes = true
end-of-line-diagnostics = "disable"
auto-pairs = false
cursorline = true
cursorcolumn = true
auto-format = false
completion-timeout = 5
rulers = [80]

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "disable"

[editor.statusline]
left = [
    "mode",
    "selections",
    "primary-selection-length",
    "position",
    "spacer",
    "position-percentage",
    "spacer",
    "separator",
    "file-name",
    "file-modification-indicator"
]
center = [
    "spinner",
    "diagnostics",
]
right = [
    "version-control",
    "spacer",
    "separator",
    "file-type",
    "file-encoding",
]

[editor.statusline.mode]
insert = "INSERT"
normal = "NORMAL"
select = "SELECT"

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.soft-wrap]
enable = true
# wrap-at-text-width = true
wrap-indicator = ""

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.insert.j]
k = "normal_mode" 
j = "@j<esc>"
